### ISSUE TITLE
Brent Jones ideas

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-rolodex#15]
We came up with some good ideas:

- [x] A timeline of users who have searched a contact. Think LinkedIn recently searched.
- [x] Add gender, race and ethnicity fields.
- [ ] Add a photo field.
- [x] Searchable tags on entities.
- [x] Background document storage. 
- [ ] Consider reimplementing dated relationships as active/inactive.
- [ ] Consider geolocating entities by primary address and allowing geo search.

**Comment by brentajones** [comment]
![happy_bear](https://cloud.githubusercontent.com/assets/1116857/10028759/cc484bce-6133-11e5-835f-2b6f4c13b42d.gif)
